# Generated by Django 5.1.3 on 2024-12-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название коллекции')),
                ('recipes', models.ManyToManyField(related_name='collections', to='recipes.recipemodel')),
            ],
        ),
    ]
