# Generated by Django 5.1.3 on 2024-12-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_collection_collectionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='recipes',
            field=models.ManyToManyField(to='recipes.recipemodel'),
        ),
    ]
