# Generated by Django 5.1.3 on 2024-12-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_collectionmodel_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='calories',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='is_optional',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='notes',
            field=models.TextField(default='Использовать теплую воду', null=True),
        ),
    ]
