# Generated by Django 5.1.3 on 2024-12-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_collectionmodel_calories_collectionmodel_is_optional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmodel',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='collectionmodel',
            name='is_optional',
        ),
        migrations.RemoveField(
            model_name='collectionmodel',
            name='notes',
        ),
        migrations.AddField(
            model_name='ingredientmodel',
            name='calories',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingredientmodel',
            name='is_optional',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ingredientmodel',
            name='notes',
            field=models.TextField(default='Использовать теплую воду', null=True),
        ),
    ]
